---
guest_docker_engine_guest_docker_packages:
  - docker.io
  - containerd
  - docker-compose-plugin
  - docker-compose-v2
  - docker-compose

guest_docker_engine_guest_docker_packages_redhat:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

guest_docker_engine_guest_docker_repo_redhat: https://download.docker.com/linux/centos/docker-ce.repo
