worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    upstream ai_backend {
        server llnode1.example.lan:11434;
        server llnode2.example.lan:11434;
        server llnode3.example.lan:11434;
        server llnode4.example.lan:11434;
        server llnode5.example.lan:11434;
    }

    server {
        listen       80;
        server_name  load_balancer.example.lan;

        location / {
            root   /usr/share/nginx/html;  # Change this to your document root
            index  index.html index.htm;
        }

        error_page  404 /404.html;
        location = /404.html {
            root   /usr/share/nginx/html;  # Path to your error page
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;  # Path to your error page
        }
    }
}
