---
- name: Remove enterprise repository source files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/pve-enterprise.list
    - /etc/apt/sources.list.d/ceph.list

- name: Install non-subscription apt sources list
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
