---
- name: Resolve OS family
  ansible.builtin.set_fact:
    ssh_hardening_resolved_os_family: >-
      {{ ansible_os_family
         | default(os | default('Debian') | capitalize) }}

- name: Determine ssh key name for hardening
  ansible.builtin.set_fact:
    ssh_hardening_ssh_key_name: >-
      {{ ssh_hardening_ssh_key_name
         | default(ssh_key_type | default('cluster')) }}

- name: Read pubkey content from control node
  ansible.builtin.set_fact:
    ssh_hardening_pubkey_path: >-
      {{ ssh_hardening_key_dir }}/{{
      ssh_hardening_ssh_key_name }}.pub

- name: Read pubkey content from control node
  ansible.builtin.set_fact:
    ssh_hardening_pubkey_content: "{{ lookup('file', ssh_hardening_pubkey_path) }}"
  changed_when: false

- name: Slurp remote authorized_keys (if present)
  ansible.builtin.slurp:
    path: /root/.ssh/authorized_keys
  register: ssh_hardening_remote_keys
  failed_when: false
  changed_when: false

- name: Set ssh_hardening_pubkey_present fact
  ansible.builtin.set_fact:
    ssh_hardening_remote_keys_decoded: "{{ (ssh_hardening_remote_keys.content | default('')) | b64decode }}"
  changed_when: false

- name: Set ssh_hardening_pubkey_present fact
  ansible.builtin.set_fact:
    ssh_hardening_pubkey_present: "{{ ssh_hardening_pubkey_content in ssh_hardening_remote_keys_decoded }}"
  changed_when: false

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart SSH service
  when:
    - ssh_hardening_disable_ssh_password | bool
    - ssh_hardening_pubkey_present | bool
